[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
shuttle-axum = "0.30.0"
shuttle-runtime = "0.30.0"
shuttle-shared-db = "0.30.0"
tokio = "1.28.2"
shuttle-fang = { path = "../.." }
fang = "0.10.4"
